runtime: java11
entrypoint: java -Xmx64m -jar /Java/target/appengine-staging/repoTown-0.0.1-SNAPSHOT.jar
instance_class: F2

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
