name: Deploy to App Engine
on:
  push:
    branches:
    - backend_dev
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Authenticate GCP
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.APPENGINE_SA_KEY }}'

    - name: Deploy
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: Java/main/src/main/appengine/app.yaml
